名称：兰州大学定时健康打卡

#控制工作流何时运行
上：
  #在推送或拉取请求事件上触发工作流，但仅针对主分支
  推：
  #每天3点、6点、8点、10点进行试打卡，注意点北京时间转为UTC时间再填下面
  时间表：
    - cron：' 0 0,2,19,22 * * * '

  #允许您从“操作”选项卡手动运行此工作流程
  工作流调度：
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # 健康打卡
  lzu_auto_check:
    name: 
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # clone当前仓库，并切换到根目录
      - uses: actions/checkout@v2

      - name: '配置python环境'
        uses: actions/setup-python@main
        with:
          python-version: '3.x'

      - name: '安装必要的python库'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: '健康打卡'
        env:
          CARDID: ${{ secrets.CARDID }}
          PASSWORD: ${{ secrets.PASSWORD }}
          SENDKEY: ${{ secrets.SENDKEY }}
          TZ: Asia/Shanghai
        run: python lzu_auto_check.py
